def findErrorNums(self, nums: list[int]) -> list[int]:
    pass