def findErrorNums(self, nums: List[int]) -> List[int]:
    pass